// Archivo generado automáticamente
export const PHONE_CODES = [
  { code: '+93', country: 'Afganistán', flag: '🇦🇫' },
  { code: '+35818', country: 'Alandia', flag: '🇦🇽' },
  { code: '+355', country: 'Albania', flag: '🇦🇱' },
  { code: '+49', country: 'Alemania', flag: '🇩🇪' },
  { code: '+376', country: 'Andorra', flag: '🇦🇩' },
  { code: '+244', country: 'Angola', flag: '🇦🇴' },
  { code: '+1264', country: 'Anguilla', flag: '🇦🇮' },
  { code: '+1268', country: 'Antigua y Barbuda', flag: '🇦🇬' },
  { code: '+966', country: 'Arabia Saudí', flag: '🇸🇦' },
  { code: '+213', country: 'Argelia', flag: '🇩🇿' },
  { code: '+54', country: 'Argentina', flag: '🇦🇷' },
  { code: '+374', country: 'Armenia', flag: '🇦🇲' },
  { code: '+297', country: 'Aruba', flag: '🇦🇼' },
  { code: '+61', country: 'Australia', flag: '🇦🇺' },
  { code: '+43', country: 'Austria', flag: '🇦🇹' },
  { code: '+994', country: 'Azerbaiyán', flag: '🇦🇿' },
  { code: '+1242', country: 'Bahamas', flag: '🇧🇸' },
  { code: '+973', country: 'Bahrein', flag: '🇧🇭' },
  { code: '+880', country: 'Bangladesh', flag: '🇧🇩' },
  { code: '+1246', country: 'Barbados', flag: '🇧🇧' },
  { code: '+32', country: 'Bélgica', flag: '🇧🇪' },
  { code: '+501', country: 'Belice', flag: '🇧🇿' },
  { code: '+229', country: 'Benín', flag: '🇧🇯' },
  { code: '+1441', country: 'Bermudas', flag: '🇧🇲' },
  { code: '+375', country: 'Bielorrusia', flag: '🇧🇾' },
  { code: '+591', country: 'Bolivia', flag: '🇧🇴' },
  { code: '+387', country: 'Bosnia y Herzegovina', flag: '🇧🇦' },
  { code: '+267', country: 'Botswana', flag: '🇧🇼' },
  { code: '+55', country: 'Brasil', flag: '🇧🇷' },
  { code: '+673', country: 'Brunei', flag: '🇧🇳' },
  { code: '+359', country: 'Bulgaria', flag: '🇧🇬' },
  { code: '+226', country: 'Burkina Faso', flag: '🇧🇫' },
  { code: '+257', country: 'Burundi', flag: '🇧🇮' },
  { code: '+975', country: 'Bután', flag: '🇧🇹' },
  { code: '+238', country: 'Cabo Verde', flag: '🇨🇻' },
  { code: '+855', country: 'Camboya', flag: '🇰🇭' },
  { code: '+237', country: 'Camerún', flag: '🇨🇲' },
  { code: '+1', country: 'Canadá', flag: '🇨🇦' },
  { code: '+599', country: 'Caribe Neerlandés', flag: '🇧🇶' },
  { code: '+974', country: 'Catar', flag: '🇶🇦' },
  { code: '+235', country: 'Chad', flag: '🇹🇩' },
  { code: '+420', country: 'Chequia', flag: '🇨🇿' },
  { code: '+56', country: 'Chile', flag: '🇨🇱' },
  { code: '+86', country: 'China', flag: '🇨🇳' },
  { code: '+357', country: 'Chipre', flag: '🇨🇾' },
  { code: '+3', country: 'Ciudad del Vaticano', flag: '🇻🇦' },
  { code: '+57', country: 'Colombia', flag: '🇨🇴' },
  { code: '+269', country: 'Comoras', flag: '🇰🇲' },
  { code: '+242', country: 'Congo', flag: '🇨🇬' },
  { code: '+243', country: 'Congo (Rep. Dem.)', flag: '🇨🇩' },
  { code: '+850', country: 'Corea del Norte', flag: '🇰🇵' },
  { code: '+82', country: 'Corea del Sur', flag: '🇰🇷' },
  { code: '+225', country: 'Costa de Marfil', flag: '🇨🇮' },
  { code: '+506', country: 'Costa Rica', flag: '🇨🇷' },
  { code: '+385', country: 'Croacia', flag: '🇭🇷' },
  { code: '+53', country: 'Cuba', flag: '🇨🇺' },
  { code: '+599', country: 'Curazao', flag: '🇨🇼' },
  { code: '+45', country: 'Dinamarca', flag: '🇩🇰' },
  { code: '+253', country: 'Djibouti', flag: '🇩🇯' },
  { code: '+1767', country: 'Dominica', flag: '🇩🇲' },
  { code: '+593', country: 'Ecuador', flag: '🇪🇨' },
  { code: '+20', country: 'Egipto', flag: '🇪🇬' },
  { code: '+503', country: 'El Salvador', flag: '🇸🇻' },
  { code: '+971', country: 'Emiratos Árabes Unidos', flag: '🇦🇪' },
  { code: '+291', country: 'Eritrea', flag: '🇪🇷' },
  { code: '+386', country: 'Eslovenia', flag: '🇸🇮' },
  { code: '+34', country: 'España', flag: '🇪🇸' },
  { code: '+1', country: 'Estados Unidos', flag: '🇺🇸' },
  { code: '+372', country: 'Estonia', flag: '🇪🇪' },
  { code: '+251', country: 'Etiopía', flag: '🇪🇹' },
  { code: '+63', country: 'Filipinas', flag: '🇵🇭' },
  { code: '+358', country: 'Finlandia', flag: '🇫🇮' },
  { code: '+679', country: 'Fiyi', flag: '🇫🇯' },
  { code: '+33', country: 'Francia', flag: '🇫🇷' },
  { code: '+241', country: 'Gabón', flag: '🇬🇦' },
  { code: '+220', country: 'Gambia', flag: '🇬🇲' },
  { code: '+995', country: 'Georgia', flag: '🇬🇪' },
  { code: '+233', country: 'Ghana', flag: '🇬🇭' },
  { code: '+350', country: 'Gibraltar', flag: '🇬🇮' },
  { code: '+30', country: 'Grecia', flag: '🇬🇷' },
  { code: '+1473', country: 'Grenada', flag: '🇬🇩' },
  { code: '+299', country: 'Groenlandia', flag: '🇬🇱' },
  { code: '+590', country: 'Guadalupe', flag: '🇬🇵' },
  { code: '+1671', country: 'Guam', flag: '🇬🇺' },
  { code: '+502', country: 'Guatemala', flag: '🇬🇹' },
  { code: '+594', country: 'Guayana Francesa', flag: '🇬🇫' },
  { code: '+44', country: 'Guernsey', flag: '🇬🇬' },
  { code: '+224', country: 'Guinea', flag: '🇬🇳' },
  { code: '+240', country: 'Guinea Ecuatorial', flag: '🇬🇶' },
  { code: '+245', country: 'Guinea-Bisáu', flag: '🇬🇼' },
  { code: '+592', country: 'Guyana', flag: '🇬🇾' },
  { code: '+509', country: 'Haití', flag: '🇭🇹' },
  { code: '+504', country: 'Honduras', flag: '🇭🇳' },
  { code: '+852', country: 'Hong Kong', flag: '🇭🇰' },
  { code: '+36', country: 'Hungría', flag: '🇭🇺' },
  { code: '+91', country: 'India', flag: '🇮🇳' },
  { code: '+62', country: 'Indonesia', flag: '🇮🇩' },
  { code: '+964', country: 'Irak', flag: '🇮🇶' },
  { code: '+98', country: 'Iran', flag: '🇮🇷' },
  { code: '+353', country: 'Irlanda', flag: '🇮🇪' },
  { code: '+47', country: 'Isla Bouvet', flag: '🇧🇻' },
  { code: '+44', country: 'Isla de Man', flag: '🇮🇲' },
  { code: '+61', country: 'Isla de Navidad', flag: '🇨🇽' },
  { code: '+672', country: 'Isla de Norfolk', flag: '🇳🇫' },
  { code: '+354', country: 'Islandia', flag: '🇮🇸' },
  { code: '+1345', country: 'Islas Caimán', flag: '🇰🇾' },
  { code: '+61', country: 'Islas Cocos o Islas Keeling', flag: '🇨🇨' },
  { code: '+682', country: 'Islas Cook', flag: '🇨🇰' },
  { code: '+298', country: 'Islas Faroe', flag: '🇫🇴' },
  { code: '+500', country: 'Islas Georgias del Sur y Sandwich del Sur', flag: '🇬🇸' },
  { code: '+500', country: 'Islas Malvinas', flag: '🇫🇰' },
  { code: '+1670', country: 'Islas Marianas del Norte', flag: '🇲🇵' },
  { code: '+692', country: 'Islas Marshall', flag: '🇲🇭' },
  { code: '+64', country: 'Islas Pitcairn', flag: '🇵🇳' },
  { code: '+677', country: 'Islas Salomón', flag: '🇸🇧' },
  { code: '+4779', country: 'Islas Svalbard y Jan Mayen', flag: '🇸🇯' },
  { code: '+690', country: 'Islas Tokelau', flag: '🇹🇰' },
  { code: '+1649', country: 'Islas Turks y Caicos', flag: '🇹🇨' },
  { code: '+268', country: 'Islas Ultramarinas Menores de Estados Unidos', flag: '🇺🇲' },
  { code: '+1340', country: 'Islas Vírgenes de los Estados Unidos', flag: '🇻🇮' },
  { code: '+1284', country: 'Islas Vírgenes del Reino Unido', flag: '🇻🇬' },
  { code: '+972', country: 'Israel', flag: '🇮🇱' },
  { code: '+39', country: 'Italia', flag: '🇮🇹' },
  { code: '+1', country: 'Jamaica', flag: '🇯🇲' },
  { code: '+81', country: 'Japón', flag: '🇯🇵' },
  { code: '+44', country: 'Jersey', flag: '🇯🇪' },
  { code: '+962', country: 'Jordania', flag: '🇯🇴' },
  { code: '+7', country: 'Kazajistán', flag: '🇰🇿' },
  { code: '+254', country: 'Kenia', flag: '🇰🇪' },
  { code: '+996', country: 'Kirguizistán', flag: '🇰🇬' },
  { code: '+686', country: 'Kiribati', flag: '🇰🇮' },
  { code: '+383', country: 'Kosovo', flag: '🇽🇰' },
  { code: '+965', country: 'Kuwait', flag: '🇰🇼' },
  { code: '+856', country: 'Laos', flag: '🇱🇦' },
  { code: '+266', country: 'Lesotho', flag: '🇱🇸' },
  { code: '+371', country: 'Letonia', flag: '🇱🇻' },
  { code: '+961', country: 'Líbano', flag: '🇱🇧' },
  { code: '+231', country: 'Liberia', flag: '🇱🇷' },
  { code: '+218', country: 'Libia', flag: '🇱🇾' },
  { code: '+423', country: 'Liechtenstein', flag: '🇱🇮' },
  { code: '+370', country: 'Lituania', flag: '🇱🇹' },
  { code: '+352', country: 'Luxemburgo', flag: '🇱🇺' },
  { code: '+853', country: 'Macao', flag: '🇲🇴' },
  { code: '+389', country: 'Macedonia del Norte', flag: '🇲🇰' },
  { code: '+261', country: 'Madagascar', flag: '🇲🇬' },
  { code: '+60', country: 'Malasia', flag: '🇲🇾' },
  { code: '+265', country: 'Malawi', flag: '🇲🇼' },
  { code: '+960', country: 'Maldivas', flag: '🇲🇻' },
  { code: '+223', country: 'Mali', flag: '🇲🇱' },
  { code: '+356', country: 'Malta', flag: '🇲🇹' },
  { code: '+212', country: 'Marruecos', flag: '🇲🇦' },
  { code: '+596', country: 'Martinica', flag: '����🇶' },
  { code: '+230', country: 'Mauricio', flag: '🇲🇺' },
  { code: '+222', country: 'Mauritania', flag: '🇲🇷' },
  { code: '+262', country: 'Mayotte', flag: '🇾🇹' },
  { code: '+52', country: 'México', flag: '🇲🇽' },
  { code: '+691', country: 'Micronesia', flag: '🇫🇲' },
  { code: '+373', country: 'Moldavia', flag: '🇲🇩' },
  { code: '+377', country: 'Mónaco', flag: '🇲🇨' },
  { code: '+976', country: 'Mongolia', flag: '🇲🇳' },
  { code: '+382', country: 'Montenegro', flag: '🇲🇪' },
  { code: '+1664', country: 'Montserrat', flag: '🇲🇸' },
  { code: '+258', country: 'Mozambique', flag: '🇲🇿' },
  { code: '+95', country: 'Myanmar', flag: '🇲🇲' },
  { code: '+264', country: 'Namibia', flag: '🇳🇦' },
  { code: '+674', country: 'Nauru', flag: '🇳🇷' },
  { code: '+977', country: 'Nepal', flag: '🇳🇵' },
  { code: '+505', country: 'Nicaragua', flag: '🇳🇮' },
  { code: '+227', country: 'Níger', flag: '🇳🇪' },
  { code: '+234', country: 'Nigeria', flag: '🇳🇬' },
  { code: '+683', country: 'Niue', flag: '🇳🇺' },
  { code: '+47', country: 'Noruega', flag: '🇳🇴' },
  { code: '+687', country: 'Nueva Caledonia', flag: '🇳🇨' },
  { code: '+64', country: 'Nueva Zelanda', flag: '🇳🇿' },
  { code: '+968', country: 'Omán', flag: '🇴🇲' },
  { code: '+31', country: 'Países Bajos', flag: '🇳🇱' },
  { code: '+92', country: 'Pakistán', flag: '🇵🇰' },
  { code: '+680', country: 'Palau', flag: '🇵🇼' },
  { code: '+970', country: 'Palestina', flag: '🇵🇸' },
  { code: '+507', country: 'Panamá', flag: '🇵🇦' },
  { code: '+675', country: 'Papúa Nueva Guinea', flag: '🇵🇬' },
  { code: '+595', country: 'Paraguay', flag: '🇵🇾' },
  { code: '+51', country: 'Perú', flag: '🇵🇪' },
  { code: '+689', country: 'Polinesia Francesa', flag: '🇵🇫' },
  { code: '+48', country: 'Polonia', flag: '🇵🇱' },
  { code: '+351', country: 'Portugal', flag: '🇵🇹' },
  { code: '+1', country: 'Puerto Rico', flag: '🇵🇷' },
  { code: '+44', country: 'Reino Unido', flag: '🇬🇧' },
  { code: '+236', country: 'República Centroafricana', flag: '🇨🇫' },
  { code: '+1', country: 'República Dominicana', flag: '🇩🇴' },
  { code: '+421', country: 'República Eslovaca', flag: '🇸🇰' },
  { code: '+262', country: 'Reunión', flag: '🇷🇪' },
  { code: '+250', country: 'Ruanda', flag: '🇷🇼' },
  { code: '+40', country: 'Rumania', flag: '🇷🇴' },
  { code: '+7', country: 'Rusia', flag: '🇷🇺' },
  { code: '+2', country: 'Sahara Occidental', flag: '🇪🇭' },
  { code: '+590', country: 'Saint Martin', flag: '🇲🇫' },
  { code: '+685', country: 'Samoa', flag: '🇼🇸' },
  { code: '+1684', country: 'Samoa Americana', flag: '🇦🇸' },
  { code: '+590', country: 'San Bartolomé', flag: '🇧🇱' },
  { code: '+1869', country: 'San Cristóbal y Nieves', flag: '🇰🇳' },
  { code: '+378', country: 'San Marino', flag: '🇸🇲' },
  { code: '+508', country: 'San Pedro y Miquelón', flag: '🇵🇲' },
  { code: '+1784', country: 'San Vicente y Granadinas', flag: '🇻🇨' },
  { code: '+2', country: 'Santa Elena, Ascensión y Tristán de Acuña', flag: '🇸🇭' },
  { code: '+1758', country: 'Santa Lucía', flag: '🇱🇨' },
  { code: '+239', country: 'Santo Tomé y Príncipe', flag: '🇸🇹' },
  { code: '+221', country: 'Senegal', flag: '🇸🇳' },
  { code: '+381', country: 'Serbia', flag: '🇷🇸' },
  { code: '+248', country: 'Seychelles', flag: '🇸🇨' },
  { code: '+232', country: 'Sierra Leone', flag: '🇸🇱' },
  { code: '+65', country: 'Singapur', flag: '🇸🇬' },
  { code: '+1721', country: 'Sint Maarten', flag: '🇸🇽' },
  { code: '+963', country: 'Siria', flag: '🇸🇾' },
  { code: '+252', country: 'Somalia', flag: '🇸🇴' },
  { code: '+94', country: 'Sri Lanka', flag: '🇱🇰' },
  { code: '+268', country: 'Suazilandia', flag: '🇸🇿' },
  { code: '+27', country: 'Sudáfrica', flag: '🇿🇦' },
  { code: '+249', country: 'Sudán', flag: '🇸🇩' },
  { code: '+211', country: 'Sudán del Sur', flag: '🇸🇸' },
  { code: '+46', country: 'Suecia', flag: '🇸🇪' },
  { code: '+41', country: 'Suiza', flag: '🇨🇭' },
  { code: '+597', country: 'Surinam', flag: '🇸🇷' },
  { code: '+66', country: 'Tailandia', flag: '🇹🇭' },
  { code: '+886', country: 'Taiwán', flag: '🇹🇼' },
  { code: '+255', country: 'Tanzania', flag: '🇹🇿' },
  { code: '+992', country: 'Tayikistán', flag: '🇹🇯' },
  { code: '+246', country: 'Territorio Británico del Océano Índico', flag: '🇮🇴' },
  { code: '+262', country: 'Tierras Australes y Antárticas Francesas', flag: '🇹🇫' },
  { code: '+670', country: 'Timor Oriental', flag: '🇹🇱' },
  { code: '+228', country: 'Togo', flag: '🇹🇬' },
  { code: '+676', country: 'Tonga', flag: '🇹🇴' },
  { code: '+1868', country: 'Trinidad y Tobago', flag: '🇹🇹' },
  { code: '+216', country: 'Túnez', flag: '🇹🇳' },
  { code: '+993', country: 'Turkmenistán', flag: '🇹🇲' },
  { code: '+90', country: 'Turquía', flag: '🇹🇷' },
  { code: '+688', country: 'Tuvalu', flag: '🇹🇻' },
  { code: '+380', country: 'Ucrania', flag: '🇺🇦' },
  { code: '+256', country: 'Uganda', flag: '🇺🇬' },
  { code: '+598', country: 'Uruguay', flag: '🇺🇾' },
  { code: '+998', country: 'Uzbekistán', flag: '🇺🇿' },
  { code: '+678', country: 'Vanuatu', flag: '🇻🇺' },
  { code: '+58', country: 'Venezuela', flag: '🇻🇪' },
  { code: '+84', country: 'Vietnam', flag: '🇻🇳' },
  { code: '+681', country: 'Wallis y Futuna', flag: '🇼🇫' },
  { code: '+967', country: 'Yemen', flag: '🇾🇪' },
  { code: '+260', country: 'Zambia', flag: '🇿🇲' },
  { code: '+263', country: 'Zimbabue', flag: '🇿🇼' }
];

export const COUNTRIES = [
  { name: 'Afganistán', code: 'AF', dial: '+93', flag: '🇦🇫' },
  { name: 'Albania', code: 'AL', dial: '+355', flag: '🇦🇱' },
  { name: 'Alemania', code: 'DE', dial: '+49', flag: '🇩🇪' },
  { name: 'Andorra', code: 'AD', dial: '+376', flag: '🇦🇩' },
  { name: 'Angola', code: 'AO', dial: '+244', flag: '🇦🇴' },
  { name: 'Arabia Saudita', code: 'SA', dial: '+966', flag: '🇸🇦' },
  { name: 'Argelia', code: 'DZ', dial: '+213', flag: '🇩🇿' },
  { name: 'Argentina', code: 'AR', dial: '+54', flag: '🇦🇷' },
  { name: 'Armenia', code: 'AM', dial: '+374', flag: '🇦🇲' },
  { name: 'Australia', code: 'AU', dial: '+61', flag: '🇦🇺' },
  { name: 'Austria', code: 'AT', dial: '+43', flag: '🇦🇹' },
  { name: 'Azerbaiyán', code: 'AZ', dial: '+994', flag: '🇦🇿' },
  { name: 'Bahamas', code: 'BS', dial: '+1', flag: '🇧🇸' },
  { name: 'Bangladés', code: 'BD', dial: '+880', flag: '🇧🇩' },
  { name: 'Bélgica', code: 'BE', dial: '+32', flag: '🇧🇪' },
  { name: 'Belice', code: 'BZ', dial: '+501', flag: '🇧🇿' },
  { name: 'Benín', code: 'BJ', dial: '+229', flag: '🇧🇯' },
  { name: 'Bolivia', code: 'BO', dial: '+591', flag: '🇧🇴' },
  { name: 'Bosnia y Herzegovina', code: 'BA', dial: '+387', flag: '🇧🇦' },
  { name: 'Brasil', code: 'BR', dial: '+55', flag: '🇧🇷' },
  { name: 'Bulgaria', code: 'BG', dial: '+359', flag: '🇧🇬' },
  { name: 'Burkina Faso', code: 'BF', dial: '+226', flag: '🇧🇫' },
  { name: 'Camerún', code: 'CM', dial: '+237', flag: '🇨🇲' },
  { name: 'Canadá', code: 'CA', dial: '+1', flag: '🇨🇦' },
  { name: 'Chile', code: 'CL', dial: '+56', flag: '🇨🇱' },
  { name: 'China', code: 'CN', dial: '+86', flag: '🇨🇳' },
  { name: 'Chipre', code: 'CY', dial: '+357', flag: '🇨🇾' },
  { name: 'Colombia', code: 'CO', dial: '+57', flag: '🇨🇴' },
  { name: 'Corea del Sur', code: 'KR', dial: '+82', flag: '🇰🇷' },
  { name: 'Costa Rica', code: 'CR', dial: '+506', flag: '🇨🇷' },
  { name: 'Croacia', code: 'HR', dial: '+385', flag: '🇭🇷' },
  { name: 'Cuba', code: 'CU', dial: '+53', flag: '🇨🇺' },
  { name: 'Dinamarca', code: 'DK', dial: '+45', flag: '🇩🇰' },
  { name: 'Ecuador', code: 'EC', dial: '+593', flag: '🇪🇨' },
  { name: 'Egipto', code: 'EG', dial: '+20', flag: '🇪🇬' },
  { name: 'El Salvador', code: 'SV', dial: '+503', flag: '🇸🇻' },
  { name: 'Emiratos Árabes Unidos', code: 'AE', dial: '+971', flag: '🇦🇪' },
  { name: 'Eslovaquia', code: 'SK', dial: '+421', flag: '🇸🇰' },
  { name: 'Eslovenia', code: 'SI', dial: '+386', flag: '🇸🇮' },
  { name: 'España', code: 'ES', dial: '+34', flag: '🇪🇸' },
  { name: 'Estados Unidos', code: 'US', dial: '+1', flag: '🇺🇸' },
  { name: 'Estonia', code: 'EE', dial: '+372', flag: '🇪🇪' },
  { name: 'Etiopía', code: 'ET', dial: '+251', flag: '🇪🇹' },
  { name: 'Filipinas', code: 'PH', dial: '+63', flag: '🇵🇭' },
  { name: 'Finlandia', code: 'FI', dial: '+358', flag: '🇫🇮' },
  { name: 'Francia', code: 'FR', dial: '+33', flag: '🇫🇷' },
  { name: 'Ghana', code: 'GH', dial: '+233', flag: '🇬🇭' },
  { name: 'Grecia', code: 'GR', dial: '+30', flag: '🇬🇷' },
  { name: 'Guatemala', code: 'GT', dial: '+502', flag: '🇬🇹' },
  { name: 'Guinea', code: 'GN', dial: '+224', flag: '🇬🇳' },
  { name: 'Haití', code: 'HT', dial: '+509', flag: '🇭🇹' },
  { name: 'Honduras', code: 'HN', dial: '+504', flag: '🇭🇳' },
  { name: 'Hong Kong', code: 'HK', dial: '+852', flag: '🇭🇰' },
  { name: 'Hungría', code: 'HU', dial: '+36', flag: '🇭🇺' },
  { name: 'India', code: 'IN', dial: '+91', flag: '🇮🇳' },
  { name: 'Indonesia', code: 'ID', dial: '+62', flag: '🇮🇩' },
  { name: 'Irak', code: 'IQ', dial: '+964', flag: '🇮🇶' },
  { name: 'Irán', code: 'IR', dial: '+98', flag: '🇮🇷' },
  { name: 'Irlanda', code: 'IE', dial: '+353', flag: '🇮🇪' },
  { name: 'Israel', code: 'IL', dial: '+972', flag: '🇮🇱' },
  { name: 'Italia', code: 'IT', dial: '+39', flag: '🇮🇹' },
  { name: 'Jamaica', code: 'JM', dial: '+1', flag: '🇯🇲' },
  { name: 'Japón', code: 'JP', dial: '+81', flag: '🇯🇵' },
  { name: 'Jordania', code: 'JO', dial: '+962', flag: '🇯🇴' },
  { name: 'Kazajistán', code: 'KZ', dial: '+7', flag: '🇰🇿' },
  { name: 'Kenia', code: 'KE', dial: '+254', flag: '🇰🇪' },
  { name: 'Kuwait', code: 'KW', dial: '+965', flag: '🇰🇼' },
  { name: 'Letonia', code: 'LV', dial: '+371', flag: '🇱🇻' },
  { name: 'Líbano', code: 'LB', dial: '+961', flag: '🇱🇧' },
  { name: 'Libia', code: 'LY', dial: '+218', flag: '🇱🇾' },
  { name: 'Lituania', code: 'LT', dial: '+370', flag: '🇱🇹' },
  { name: 'Luxemburgo', code: 'LU', dial: '+352', flag: '🇱🇺' },
  { name: 'Macedonia del Norte', code: 'MK', dial: '+389', flag: '🇲🇰' },
  { name: 'Malasia', code: 'MY', dial: '+60', flag: '🇲🇾' },
  { name: 'Marruecos', code: 'MA', dial: '+212', flag: '🇲🇦' },
  { name: 'México', code: 'MX', dial: '+52', flag: '🇲🇽' },
  { name: 'Nicaragua', code: 'NI', dial: '+505', flag: '🇳🇮' },
  { name: 'Nigeria', code: 'NG', dial: '+234', flag: '🇳🇬' },
  { name: 'Noruega', code: 'NO', dial: '+47', flag: '🇳🇴' },
  { name: 'Nueva Zelanda', code: 'NZ', dial: '+64', flag: '🇳🇿' },
  { name: 'Países Bajos', code: 'NL', dial: '+31', flag: '🇳🇱' },
  { name: 'Pakistán', code: 'PK', dial: '+92', flag: '🇵🇰' },
  { name: 'Panamá', code: 'PA', dial: '+507', flag: '🇵🇦' },
  { name: 'Paraguay', code: 'PY', dial: '+595', flag: '🇵🇾' },
  { name: 'Perú', code: 'PE', dial: '+51', flag: '🇵🇪' },
  { name: 'Polonia', code: 'PL', dial: '+48', flag: '🇵🇱' },
  { name: 'Portugal', code: 'PT', dial: '+351', flag: '🇵🇹' },
  { name: 'Puerto Rico', code: 'PR', dial: '+1', flag: '🇵🇷' },
  { name: 'Qatar', code: 'QA', dial: '+974', flag: '🇶🇦' },
  { name: 'Reino Unido', code: 'GB', dial: '+44', flag: '🇬🇧' },
  { name: 'República Checa', code: 'CZ', dial: '+420', flag: '🇨🇿' },
  { name: 'República Dominicana', code: 'DO', dial: '+1', flag: '🇩🇴' },
  { name: 'Rumania', code: 'RO', dial: '+40', flag: '🇷🇴' },
  { name: 'Rusia', code: 'RU', dial: '+7', flag: '🇷🇺' },
  { name: 'Senegal', code: 'SN', dial: '+221', flag: '🇸🇳' },
  { name: 'Serbia', code: 'RS', dial: '+381', flag: '🇷🇸' },
  { name: 'Singapur', code: 'SG', dial: '+65', flag: '🇸🇬' },
  { name: 'Siria', code: 'SY', dial: '+963', flag: '🇸🇾' },
  { name: 'Sudáfrica', code: 'ZA', dial: '+27', flag: '🇿🇦' },
  { name: 'Sudán', code: 'SD', dial: '+249', flag: '🇸🇩' },
  { name: 'Suecia', code: 'SE', dial: '+46', flag: '🇸🇪' },
  { name: 'Suiza', code: 'CH', dial: '+41', flag: '🇨🇭' },
  { name: 'Tailandia', code: 'TH', dial: '+66', flag: '🇹🇭' },
  { name: 'Tanzania', code: 'TZ', dial: '+255', flag: '🇹🇿' },
  { name: 'Trinidad y Tobago', code: 'TT', dial: '+1', flag: '🇹🇹' },
  { name: 'Túnez', code: 'TN', dial: '+216', flag: '🇹🇳' },
  { name: 'Turquía', code: 'TR', dial: '+90', flag: '🇹🇷' },
  { name: 'Ucrania', code: 'UA', dial: '+380', flag: '🇺🇦' },
  { name: 'Uganda', code: 'UG', dial: '+256', flag: '🇺🇬' },
  { name: 'Uruguay', code: 'UY', dial: '+598', flag: '🇺🇾' },
  { name: 'Venezuela', code: 'VE', dial: '+58', flag: '🇻🇪' },
  { name: 'Vietnam', code: 'VN', dial: '+84', flag: '🇻🇳' },
  { name: 'Yemen', code: 'YE', dial: '+967', flag: '🇾🇪' },
  { name: 'Zambia', code: 'ZM', dial: '+260', flag: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZW', dial: '+263', flag: '🇿🇼' },
  { name: 'Otro', code: 'XX', dial: '+', flag: '🌍' },
]
